[cubi.metadata]
pid = "undefined"
version = "1.4.0"

[tool.black]
line-length = 88

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.messages_control]
disable=[
  "logging-fstring-interpolation",
  "useless-return",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"
